apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "errbit.fullname" . }}
  labels:
    app: {{ template "errbit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "errbit.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["docker-entrypoint.sh"]
          args: ["puma", "-C", "config/puma.default.rb"]
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
            - name: MONGODB_USERNAME
              value: {{ template "errbit.mongodbUsername" . }}
            {{- if .Values.mongodb.enabled }}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mongodb.fullname" . }}
                  key: mongodb-password
            {{- end }}
            - name: MONGODB_HOST
              value: {{ template "errbit.mongodbHost" . }}
            - name: MONGODB_PORT
              value: {{ template "errbit.mongodbPort" . }}
            - name: MONGODB_DATABASE
              value: {{ template "errbit.mongodbDatabase" . }}
          envFrom:
            - secretRef:
                name: {{ template "errbit.fullname" . }}
            - configMapRef:
                name: {{ template "errbit.fullname" . }}
          volumeMounts:
            - name: entrypoint-config-volume
              mountPath: /usr/local/bin/docker-entrypoint.sh
              subPath: docker-entrypoint.sh
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: entrypoint-config-volume
          configMap:
            name: {{ template "errbit.fullname" . }}-files
            items:
              - key: docker-entrypoint.sh
                path: docker-entrypoint.sh
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
