apiVersion: v1
kind: Secret
metadata:
  name: {{ template "errbit.fullname" . }}
  labels:
    app: {{ template "errbit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.configSecure }}
  {{ $key | upper }}: {{ $value | b64enc | quote}}
  {{- end }}
